### PR TITLE
Improve PhantomData usage

### PR DESCRIPTION
**Pull request by dwijnand**
Apply the suggestions in:

* https://www.reddit.com/r/rust/comments/8ls25e/blog_post_typed_key_pattern/dzk1ttc/
* https://www.reddit.com/r/rust/comments/8ls25e/blog_post_typed_key_pattern/dzk1w8l/

### CODE REVIEW

**Comment by matklad** [comment]
Thanks! I don't know if we really need all of this, so I suggest to write the tests which exemplify the change in the behavior behavior. This will be tricky, because vatriance and dropchk are tricky, but it could be a fun learning exercise. 

1) Clone: the change is actually uncontroversial, however it seems that tests pass even if we replace manual impls with derive. Let's add a test which shows why we need explicit impls?

2) Variance: I think covariance is probably the expected behavior here, but we need a test. To write a test, I think we could use serde's [support for borrowing](https://serde.rs/lifetimes.html#borrowing-data-in-a-derived-impl). 

3) dropcheck. This one is going to be tricky, the docs are here https://doc.rust-lang.org/nomicon/dropck.html.

I *think* I know how tests for 2 and 3 should look like, but the code I have in mind is pretty bizarre and unrealistic. I wonder if you could come up with simpler examples than mine, so I am not going to disclose my ideas right now :)

**Comment by dwijnand** [comment]
(when I find some time, soon)

**Comment by dwijnand** [comment]
> I wonder if you could come up with simpler examples than mine, so I am not going to disclose my ideas right now :)

Most probably not, seeing as I'm still very much learning Rust.

**Comment by dwijnand** [comment]
OK. Sitting down and re-reading what you wrote and thinking about I came to the realisation that I have no idea how to do this. 😄

So I'll close this, but if you (or someone) works on this, I'd be keen to learn from it.

**Pull request closed without merging**
